In [ ]:
import pandas as pd
import math
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#to solve system of linear equation by gauss-elimination with partial pivoting
n = int(input("Enter augumented matrix"))
A = []
for i in range(n):
  A.append (list(map(float, input("Enter {i+1}th row: split()"))))
A = np.array(A)
print ("the augu,emted ,atric is :", A)

for i in range(n):
  p_row = np.argmax(abs(A[i:,i]))+i
  A[[i, p_row]] = A[[p_row, i]]
  for j in range(i+1,n):
    A[j] = A[j] - A[j,i] * A[i]/A[j]
print ("The upper triangular matrix is:")
print (np.matrix[A])
x = np.zero(n)
for i in range (n-1, -1, -1):
  if j != i:
    x[i] = (A[i, -i] - np.sum(A[i, j]* x[j])/A[i,j])
print ("The solution is:")
print (x)
for i in range(n):
  print (f'x{i+1} = {x[i]}')



KeyboardInterrupt: Interrupted by user

In [ ]:
import numpy as np

# Step 1: Input augmented matrix
n = int(input("Enter number of unknowns (n): "))
A = []
for i in range(n):
    row = list(map(float, input(f"Enter row {i+1} (space-separated, including constants): ").split()))
    A.append(row)

A = np.array(A)
print("The augmented matrix is:\n", A)

# Step 2: Forward Elimination with Partial Pivoting
for i in range(n):
    # Partial Pivoting
    p_row = np.argmax(abs(A[i:, i])) + i
    if A[p_row, i] == 0:
        raise ValueError("Matrix is singular or nearly singular.")
    A[[i, p_row]] = A[[p_row, i]]

    for j in range(i + 1, n):
        factor = A[j, i] / A[i, i]
        A[j] = A[j] - factor * A[i]

print("The upper triangular matrix is:\n", A)

# Step 3: Back Substitution
x = np.zeros(n)
for i in range(n - 1, -1, -1):
    x[i] = (A[i, -1] - np.dot(A[i, i+1:n], x[i+1:n])) / A[i, i]

# Step 4: Output solution
print("The solution is:")
for i in range(n):
    print(f"x{i+1} = {x[i]}")


Enter number of unknowns (n): 4
Enter row 1 (space-separated, including constants): 1 -2 3 1
Enter row 2 (space-separated, including constants): 4 1 -1 -3
Enter row 3 (space-separated, including constants): 2 -3 4 2
Enter row 4 (space-separated, including constants): 3 2 -1 -1
The augmented matrix is:
 [[ 1. -2.  3.  1.]
 [ 4.  1. -1. -3.]
 [ 2. -3.  4.  2.]
 [ 3.  2. -1. -1.]]
The upper triangular matrix is:
 [[ 4.          1.         -1.         -3.        ]
 [ 0.         -3.5         4.5         3.5       ]
 [ 0.          0.          1.35714286  2.5       ]
 [ 0.          0.          0.         -1.15789474]]
The solution is:
x1 = 0.0
x2 = -0.0
x3 = 0.0
x4 = 1.0
